#!/usr/bin/env bash
_GoogliserCompletion ()
{
  # Pointer to current completion word.
  # By convention, it's named "cur" but this isn't strictly necessary.
  local cur

  OPTS='-d -E -h -L -q -s -S -z -a -b -G -i -l -m -n -o -p -P -r -R -t -T -u --debug \
  --exact-search --help --lightning --links-only --no-colour --no-color --safesearch-off \
  --quiet --random --reindex-rename --save-links --skip-no-size --aspect-ratio \
  --border-pixels --colour --color --exclude-links --exclude-words --format --gallery \
  --input-links --input-phrases --lower-size --minimum-pixels --number --output --parallel \
  --phrase --recent --retries --sites --thumbnails --timeout --title --type --upper-size --usage-rights'

  COMPREPLY=()   # Array variable storing the possible completions.
  cur=${COMP_WORDS[COMP_CWORD]}

  case "$cur" in
    -*)
    COMPREPLY=( $( compgen -W "${OPTS}" -- ${cur} ) );;
  esac

  return 0
}

complete -F _GoogliserCompletion googliser
